name: Auto Raise Pull Requests
on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'chore/*'
      - 'cicd/*'

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Raise Pull Request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "develop"
        pr_title: "AutoPR to Develop"
        pr_body: "Auto-raised PR to Develop"
        pr_draft: false
        pr_label: "AutoCICD"
        github_token: "${{ secrets.HUB_TOKEN }}"
