name: Pull Request Tasks
on:
  pull_request:
    types: [opened]
    branches:
      - develop

jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pull-request-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
